<?php

namespace AppBundle\Repository;

/**
 * Big5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Big5Repository extends \Doctrine\ORM\EntityRepository
{
}
