<?php

namespace AppBundle\Repository;

/**
 * CultureFitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultureFitRepository extends \Doctrine\ORM\EntityRepository
{
}
