<?php

namespace AppBundle\Repository;

/**
 * PartnerViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerViewRepository extends \Doctrine\ORM\EntityRepository
{
}
