<?php
/**
 * Created by PhpStorm.
 * User: biovor
 * Date: 10/08/17
 * Time: 10:08
 */

namespace AppBundle\Repository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{

}