<?php

namespace AppBundle\Repository;

/**
 * SourcinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourcinkRepository extends \Doctrine\ORM\EntityRepository
{
}
